DELETE FROM Crimes_in_Toronto
WHERE OCC_YEAR = 'None';

ALTER TABLE Crimes_in_Toronto
ALTER COLUMN OCC_YEAR TYPE INTEGER USING OCC_YEAR::INTEGER;

DELETE FROM Crimes_in_Toronto
WHERE OCC_DAY = 'None';

ALTER TABLE Crimes_in_Toronto
ALTER COLUMN OCC_DAY TYPE INTEGER USING OCC_YEAR::INTEGER;

DELETE FROM Crimes_in_Toronto
WHERE OCC_DOY = 'None';

ALTER TABLE Crimes_in_Toronto
ALTER COLUMN OCC_DOY TYPE INTEGER USING OCC_YEAR::INTEGER;

ALTER TABLE Crimes_in_Toronto
DROP COLUMN HOOD_140;

ALTER TABLE Crimes_in_Toronto
DROP COLUMN NEIGHBORHOOD_140;




ALTER TABLE Crimes_in_Toronto
ADD PRIMARY KEY (_id);

DELETE FROM Crimes_in_Toronto
WHERE OCC_YEAR < 2020;


SELECT UCR_CODE, UCR_EXT, (UCR_CODE::TEXT || UCR_EXT::TEXT)::INTEGER as UCR
FROM Crimes_in_Toronto LIMIT 10;

ALTER TABLE Crimes_in_Toronto
ADD UCR INTEGER;

UPDATE Crimes_in_Toronto
SET UCR = ((UCR_CODE::TEXT || UCR_EXT::TEXT)::INTEGER);
