CREATE TABLE toronto_crimes (
    _id INTEGER,
    EVENT_UNIQUE_ID TEXT,
    REPORT_DATE DATE,
    OCC_DATE DATE,
    REPORT_HOUR INTEGER,
    OCC_HOUR INTEGER,
    DIVISION TEXT,
    UCR INTEGER,
    LONG_WGS84 DOUBLE PRECISION,
    LAT_WGS84 DOUBLE PRECISION,
    PRIMARY KEY (_id),
    FOREIGN KEY (UCR) REFERENCES crime_info(UCR),
    FOREIGN KEY (LONG_WGS84, LAT_WGS84) REFERENCES location(LONG_WGS84, LAT_WGS84),
    FOREIGN KEY (OCC_DATE) REFERENCES occurance_date(OCCURANCE_FULL_DATE),
    FOREIGN KEY (REPORT_DATE) REFERENCES report_date(REPORT_FULL_DATE)
);


CREATE TABLE report_date (
    REPORT_FULL_DATE DATE,
    REPORT_YEAR INTEGER,
    REPORT_MONTH TEXT,
    REPORT_DAY INTEGER,
    REPORT_DOY INTEGER,
    REPORT_DOW TEXT,
    PRIMARY KEY (REPORT_FULL_DATE)
);

CREATE TABLE occurance_date (
    OCCURANCE_FULL_DATE DATE,
    OCC_YEAR INTEGER,
    OCC_MONTH TEXT,
    OCC_DAY INTEGER,
    OCC_DOY INTEGER ,
    OCC_DOW TEXT,
    PRIMARY KEY (OCCURANCE_FULL_DATE)
);

CREATE TABLE location_type (
    PREMIS_TYPE TEXT,
    LOCATION_TYPE TEXT,
    PRIMARY KEY (PREMIS_TYPE)
);

CREATE TABLE location (
    LONG_WGS84 DOUBLE PRECISION,
    LAT_WGS84 DOUBLE PRECISION,
    HOOD_158 TEXT,
    NEIGHBORHOOD_158 TEXT,
    PREMIS_TYPE TEXT,
    PRIMARY KEY (LONG_WGS84, LAT_WGS84),
    FOREIGN KEY (PREMIS_TYPE) REFERENCES location_type(PREMIS_TYPE)
);


CREATE TABLE crime_info (
    UCR INTEGER,
    OFFENSE TEXT,
    MCI_CATEGORY TEXT,
    PRIMARY KEY (UCR)
);



INSERT INTO toronto_crimes (
    _id,
    EVENT_UNIQUE_ID,
    REPORT_DATE,
    OCC_DATE,
    REPORT_HOUR,
    OCC_HOUR,
    DIVISION,
    UCR,
    LONG_WGS84,
    LAT_WGS84
) SELECT 
    _id, 
    EVENT_UNIQUE_ID,
    REPORT_DATE,
    OCC_DATE,
    REPORT_HOUR,
    OCC_HOUR,
    DIVISION,
    UCR,
    LONG_WGS84,
    LAT_WGS84
    FROM Crimes_in_Toronto;

INSERT INTO report_date (
    REPORT_FULL_DATE,
    REPORT_YEAR,
    REPORT_MONTH,
    REPORT_DAY,
    REPORT_DOY,
    REPORT_DOW
) SELECT DISTINCT
    REPORT_DATE UNIQUE,
    REPORT_YEAR,
    REPORT_MONTH,
    REPORT_DAY,
    REPORT_DOY,
    REPORT_DOW
    FROM Crimes_in_Toronto
    ON CONFLICT (REPORT_FULL_DATE) DO NOTHING;

INSERT INTO occurance_date (
    OCCURANCE_FULL_DATE,
    OCC_YEAR,
    OCC_MONTH,
    OCC_DAY,
    OCC_DOY,
    OCC_DOW
) SELECT DISTINCT
    OCC_DATE,
    OCC_YEAR,
    OCC_MONTH,
    OCC_DAY,
    OCC_DOY,
    OCC_DOW
    FROM Crimes_in_Toronto
    ON CONFLICT (OCCURANCE_FULL_DATE) DO NOTHING;

INSERT INTO location_type (
    PREMIS_TYPE,
    LOCATION_TYPE
) SELECT DISTINCT
    PREMIS_TYPE,
    LOCATION_TYPE
    FROM Crimes_in_Toronto
    ON CONFLICT (PREMIS_TYPE) DO NOTHING;

INSERT INTO location (
    LONG_WGS84,
    LAT_WGS84,
    HOOD_158,
    NEIGHBORHOOD_158,
    PREMIS_TYPE
) SELECT DISTINCT
    LONG_WGS84,
    LAT_WGS84,
    HOOD_158,
    NEIGHBORHOOD_158,
    PREMIS_TYPE
    FROM Crimes_in_Toronto
    WHERE LONG_WGS84 IS NOT NULL AND LAT_WGS84 IS NOT NULL
    ON CONFLICT (LONG_WGS84, LAT_WGS84) DO NOTHING;


INSERT INTO crime_info (
    UCR,
    OFFENSE,
    MCI_CATEGORY
) SELECT DISTINCT
    UCR,
    OFFENSE,
    MCI_CATEGORY
    FROM Crimes_in_Toronto
    ON CONFLICT (UCR) DO NOTHING;
